version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    expose:
      - "8231"
    ports:
      - "8231:8231"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    command: -p 8231

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ericklucas@id.uff.br"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres
